// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IPepProxy {
    id?: string;
    oauth_client_id?: <FILL>;
}

export default class PepProxy {
    readonly _id: string | undefined;

    get id(): string | undefined {
        return this._id;
    }

    readonly _oauth_client_id: string | undefined;

    get oauthClientId(): string | undefined {
        return this._oauth_client_id;
    }

    constructor(props: IPepProxy) {
        if (typeof props.id === 'string') {
            this._id = props.id.trim();
        }
        if (typeof props.oauth_client_id === 'string') {
            this._oauth_client_id = props.oauth_client_id.trim();
        }
    }

    serialize(): IPepProxy {
        const data: IPepProxy = {};
        if (typeof this._id !== 'undefined') {
            data.id = this._id;
        }
        if (typeof this._oauth_client_id !== 'undefined') {
            data.oauth_client_id = this._oauth_client_id;
        }
        return data;
    }

    validate(): string[] {
        const validate = {
            id: !this._id
                ? true
                : typeof this._id === 'string' && !this._id
                ? true
                : this._id,
            oauth_client_id: !this._oauth_client_id
                ? true
                : typeof this._oauth_client_id === 'string' &&
                  !this._oauth_client_id
                ? true
                : this._oauth_client_id,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IPepProxy>): PepProxy {
        return new PepProxy({...this.serialize(), ...props});
    }
}
